# nixpacks.toml

[phases.setup]
# Paquetes que Nixpacks instalará para tu build
packages = [
  "php",
  "php-pdo_mysql",
  "php-zip",
  "php-curl",
  "php-mbstring",
  "php-xml",
  "composer",
  "nodejs",
  "npm",
  "git",
  "unzip"
]

[phases.install]
commands = [
  "composer install --no-dev --optimize-autoloader",
  "npm install"
]

[phases.build]
commands = [
  "npm run build",
  "php artisan migrate --force",
  "php artisan db:seed --class=UserSeeder",
  "php artisan db:seed --class=InsectSeeder",
  "php artisan optimize",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[phases.start]
commands = [
  "php artisan serve --host=0.0.0.0 --port=$PORT"
]

[env]
APP_ENV = "production"
APP_DEBUG = "false"
