[phases.setup]
packages = ["php", "composer", "nodejs", "npm"]

[phases.install]
commands = [
  "composer install --no-dev --optimize-autoloader",
  "npm install"
]

[phases.build]
commands = [
  "npm run build"
]

[phases.start]
commands = [
  "php artisan serve --host=0.0.0.0 --port=$PORT"
]