[phases.setup]
nixpkgsArchive = "nixpkgs/nixos-23.05"
packages = [
  "php82",
  "php82Packages.composer",
  "php82Extensions.mbstring",
  "php82Extensions.xml",
  "php82Extensions.curl",
  "php82Extensions.zip",
  "php82Extensions.pdo_mysql",
  "nodejs_20",
  "npm"
]

[phases.install]
commands = [
  "composer install --no-dev --optimize-autoloader",
  "npm install"
]

[phases.build]
commands = [
  "npm run build",
  "php artisan migrate --force",
  "php artisan db:seed --class=UserSeeder",
  "php artisan db:seed --class=InsectSeeder",
  "php artisan optimize",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"