[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "nodejs", "mariadb"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "rm -rf node_modules package-lock.json",
  "npm cache clean --force",
  "npm install --ignore-scripts --no-optional",
  "npm run build",
  "php artisan migrate --force",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8080"